# Generated by Django 4.1.7 on 2023-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commType', models.CharField(help_text='choisit le type de la command', max_length=1, verbose_name='type de command')),
                ('tableNum', models.IntegerField(help_text='enter le numero de la table', verbose_name='numero de table')),
                ('dateComm', models.DateTimeField(auto_now_add=True, verbose_name='temps creation de la command')),
                ('encaisser', models.BooleanField(default=False, verbose_name='status d encaissemnt')),
                ('encaissementTime', models.DateTimeField(auto_now_add=True, verbose_name='temps encaissement')),
                ('flaged', models.BooleanField(verbose_name='modification au command')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(help_text='entrer le nom de produit', max_length=30, verbose_name='nom de produit')),
                ('prodPrix', models.IntegerField(help_text='prix de produit', verbose_name='prix de produit')),
                ('prodCat', models.CharField(choices=[('1', 'Traditionelle'), ('2', 'Modern'), ('3', 'Boissant')], help_text='choisit la categorie de ce produit', max_length=1, verbose_name='categorie de produit')),
                ('isActive', models.BooleanField(help_text='activer ou desactiver ce produit', verbose_name='status de produit')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('userPriority', models.CharField(choices=[('1', 'caissier admin'), ('2', 'caissier'), ('3', 'serveur')], max_length=1, verbose_name='usertype')),
            ],
        ),
    ]
