# Generated by Django 4.1.7 on 2023-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_command_prods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='commType',
            field=models.CharField(choices=[('1', 'emporter'), ('2', 'a table')], help_text='choisit le type de la command', max_length=1, verbose_name='type de command'),
        ),
    ]
