# Generated by Django 4.1.7 on 2023-03-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_command_commtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='commPrice',
            field=models.IntegerField(default=0, verbose_name='prix total command'),
        ),
    ]
