# Generated by Django 4.1.7 on 2023-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='prods_quantity',
            field=models.CharField(default='{}', max_length=750),
        ),
    ]
