# Generated by Django 4.1.4 on 2023-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_command_prods_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='prods_quantity',
            field=models.CharField(default='{}', max_length=750),
        ),
    ]
