# Generated by Django 4.1.7 on 2023-03-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_command_flaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='commType',
            field=models.CharField(choices=[('1', 'emporter'), ('2', 'a table')], default=1, help_text='choisit le type de la command', max_length=1, verbose_name='type de command'),
        ),
        migrations.AlterField(
            model_name='command',
            name='tableNum',
            field=models.IntegerField(default=-1, help_text='enter le numero de la table', verbose_name='numero de table'),
        ),
    ]
