# Generated by Django 4.1.7 on 2023-03-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_command_commtype_alter_command_tablenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='tableNum',
            field=models.CharField(default='-1', help_text='enter le numero de la table', max_length=2, verbose_name='numero de table'),
        ),
    ]
