# Generated by Django 4.1.7 on 2023-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_command_tablenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='commType',
            field=models.CharField(choices=[('1', 'emporter'), ('2', 'a table')], default='1', help_text='choisit le type de la command', max_length=1, verbose_name='type de command'),
        ),
    ]
