# Generated by Django 4.1.4 on 2023-03-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_command_prods_quantity'),
        ('main', '0012_alter_command_commtype'),
    ]

    operations = [
    ]
