# Generated by Django 4.1.7 on 2023-04-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20230329_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodCat',
            field=models.IntegerField(choices=[('1', 'Traditionelle'), ('2', 'Modern'), ('3', 'Boissant')], help_text='choisit la categorie de ce produit', max_length=1, verbose_name='categorie de produit'),
        ),
    ]
