# Generated by Django 4.1.7 on 2023-04-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_products_prodcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodCat',
            field=models.IntegerField(choices=[('1', 'Traditionel'), ('2', 'Modern'), ('3', 'Boissant')], help_text='choisit la categorie de ce produit', verbose_name='categorie de produit'),
        ),
    ]
