# Generated by Django 4.1.7 on 2023-04-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_products_prodcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='flaged_prods',
            field=models.CharField(default='{}', max_length=750),
        ),
    ]
