# Generated by Django 4.1.7 on 2023-04-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_products_deleted_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='isCanceled',
            field=models.BooleanField(default=False, verbose_name='si la command est anuller'),
        ),
    ]
