# Generated by Django 4.1.7 on 2023-04-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_command_iscanceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tablesNum',
            field=models.IntegerField(default=0),
        ),
    ]
